### ISSUE TITLE
How to use

### ISSUE THREAD

**Issue by haoyanbing** [dzwillia/vue-grid#1]
Hao to use this to my vue-cli project?

**Comment by dzwillia** [comment]
Hi there!

If you could please elaborate a little on what you're trying to do that might help me understand how to answer a bit better.

Thanks!

**Comment by dzwillia** [comment]
I'd love to help you out, but I need a more concrete question in order to help you. If I don't hear back in a week or two, I'll close out this issue. Thanks!
