### ISSUE TITLE
Docs link is broken

### ISSUE THREAD

**Issue by takotuesday** [dzwillia/vue-grid#2]
The link to the documentation in the `README.md` file returns you to the GitHub page for `vue-grid`

**Comment by dzwillia** [comment]
Hi there!

Thanks for your feedback!

The docs link is not broken -- the README.md file is the documentation for the grid right now. Referencing the README file on GitHub is done for sites like npmjs.com which uses this file as well.

I'm working on formalizing the documentation further in the coming weeks and months.
