### ISSUE TITLE
Demo is not working.

### ISSUE THREAD

**Issue by placidlyUnsalted** [dzwillia/vue-grid#3]
https://dzwillia.github.io/vue-grid/ has problem with external json.

**Comment by dzwillia** [comment]
Good eye! We updated the API server that I'm using for vue-grid over the weekend and are sorting out some of the data feeds. I'll do my best to have it sorted here in the next day or two.

**Comment by placidlyUnsalted** [comment]
Great! Thanks for the information.  I'll stop by in a couple of days. Good luck with the project!

**Comment by placidlyUnsalted** [comment]
All working now!

**Comment by dzwillia** [comment]
Indeed! We updated the data server last week.

Thanks again for the heads up. Glad it's working for you!
