### ISSUE TITLE
Demo in provided link does not manage to load the data (404)

### ISSUE THREAD

**Issue by sscholle** [dzwillia/vue-grid#4]
The Demo link in the readme works, however the data it tries to load never arrives: see 404 in the console when opening demo

**Comment by dzwillia** [comment]
Hi! Thanks for spotting this. We updated the API server that I'm using for the vue-grid demo this past week and are sorting out some of the data feeds. I'll do my best to have it sorted here by the end of the week.

**Comment by hanxue** [comment]
Hello @dzwillia , is the source data JSON file available anywhere? I have done a demo fix at https://github.com/hanxue/vue-grid, and result can be seen at https://hanxue.github.io/vue-grid/#/interactions

**Comment by dzwillia** [comment]
Hi @hanxue,

The reference to the source data has been updated and the demo now works again.

Thanks for your patience! Let me know if you have any other issues or questions!

**Comment by Aymkdn** [comment]
Hi

I get a 404 error too when checking the console for the demo.

**Comment by dzwillia** [comment]
Sorry -- we did another backend API update to our [Flex.io serverless data feeds](https://www.flex.io) , which I'm using for the grid's data. It's fixed again. Thanks for the heads up!
